### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F10-2

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F10-2/main#203]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [ ] All issues in this milestone are closed(:exclamation:)
   * [ ] Milestone explicitly closed(:exclamation:)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @woblek for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-2/main/issues/153 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/58 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/51 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/50 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/27 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @zyleet for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-2/main/issues/170 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/154 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/149 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/107 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/51 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/50 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/43 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/24 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @kanequah for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-2/main/issues/56 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/51 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/50 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/29 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/18 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/15 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @manaswini05 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-2/main/issues/129 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/128 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/127 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/51 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/50 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/36 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/35 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/28 https://github.com/AY1920S1-CS2113T-F10-2/main/issues/19 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @jtankw3

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
